version: '3'
services:
  db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    #ports:
    #  - 5437:5432/tcp
    environment:
    - POSTGRES_PASSWORD=odoo
    - POSTGRES_USER=odoo
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata
  odoo12:
    build: .
    depends_on:
      - db
    ports:
      - "8017:8069/tcp"
    tty: true
    volumes:
      - odoo-data:/var/lib/odoo
      - ./modules:/mnt/extra-addons
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=odoo
      - PGPASSWORD=odoo
volumes:
  db-data:
    driver: local
  odoo-data:
    driver: local
